### ISSUE TITLE
ImportError: DLL load failed while importing fugashi: The specified module could not be found.

### ISSUE THREAD

**Issue by YinnVI** [kha-white/mokuro#5]
```
C:\Users\Seven7>mokuro "C:\A\Summertime renderer v01"

Paths to process:

C:\A\Summertime renderer v01

Each of the paths above will be treated as one volume. Continue? [yes/no]
yes
2022-05-05 13:18:13.152 | INFO     | mokuro.run:run:40 - Processing 1/1: C:\A\Summertime renderer v01
Processing pages...:   0%|                                                                                                                                                                                          | 0/294 [00:00<?, ?it/s]2022-05-05 13:18:13.170 | INFO     | mokuro.manga_page_ocr:__init__:30 - Initializing text detector
2022-05-05 13:18:13.614 | INFO     | manga_ocr.ocr:__init__:13 - Loading OCR model from kha-white/manga-ocr-base
Processing pages...:   0%|                                                                                                                                                                                          | 0/294 [00:06<?, ?it/s]
2022-05-05 13:18:19.524 | ERROR    | mokuro.run:run:44 - Error while processing C:\A\Summertime renderer v01
Traceback (most recent call last):

  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\Seven7\AppData\...
           │         └ <code object <module> at 0x000002AF10CFFF50, file "C:\Users\Seven7\AppData\Roaming\Python\Python39\Scripts\mokuro.exe\__...
           └ <function _run_code at 0x000002AF104DECA0>

  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\Seven7\AppData\...
         └ <code object <module> at 0x000002AF10CFFF50, file "C:\Users\Seven7\AppData\Roaming\Python\Python39\Scripts\mokuro.exe\__...

  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\Scripts\mokuro.exe\__main__.py", line 7, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x000002AF10CEC280>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\mokuro\__main__.py", line 7, in main
    fire.Fire(run)
    │    │    └ <function run at 0x000002AF36438CA0>
    │    └ <function Fire at 0x000002AF36438F70>
    └ <module 'fire' from 'C:\\Users\\Seven7\\AppData\\Roaming\\Python\\Python39\\site-packages\\fire\\__init__.py'>
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'mokuro'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(verbose=False, interactive=False, separator='-', completion=None, help=False, trace=False)
                      │     │          └ ['C:\\A\\Summertime renderer v01']
                      │     └ <function run at 0x000002AF36438CA0>
                      └ <function _Fire at 0x000002AF364C0F70>
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x000002AF364C20D0>
    └ <function run at 0x000002AF36438CA0>
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['C:\\A\\Summertime renderer v01']
                └ <function run at 0x000002AF36438CA0>
> File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\mokuro\run.py", line 42, in run
    ovg.process_dir(path, as_one_file=as_one_file)
    │   │           │                 └ True
    │   │           └ WindowsPath('C:/A/Summertime renderer v01')
    │   └ <function OverlayGenerator.process_dir at 0x000002AF36438790>
    └ <mokuro.overlay_generator.OverlayGenerator object at 0x000002AF364AE490>
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\mokuro\overlay_generator.py", line 82, in process_dir
    self.init_models()
    │    └ <function OverlayGenerator.init_models at 0x000002AF36438700>
    └ <mokuro.overlay_generator.OverlayGenerator object at 0x000002AF364AE490>
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\mokuro\overlay_generator.py", line 55, in init_models
    self.mpocr = MangaPageOcr(self.pretrained_model_name_or_path, self.force_cpu, **self.kwargs)
    │    │       │            │    │                              │    │            │    └ {}
    │    │       │            │    │                              │    │            └ <mokuro.overlay_generator.OverlayGenerator object at 0x000002AF364AE490>
    │    │       │            │    │                              │    └ False
    │    │       │            │    │                              └ <mokuro.overlay_generator.OverlayGenerator object at 0x000002AF364AE490>
    │    │       │            │    └ 'kha-white/manga-ocr-base'
    │    │       │            └ <mokuro.overlay_generator.OverlayGenerator object at 0x000002AF364AE490>
    │    │       └ <class 'mokuro.manga_page_ocr.MangaPageOcr'>
    │    └ None
    └ <mokuro.overlay_generator.OverlayGenerator object at 0x000002AF364AE490>
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\mokuro\manga_page_ocr.py", line 34, in __init__
    self.mocr = MangaOcr(pretrained_model_name_or_path, force_cpu)
    │           │        │                              └ False
    │           │        └ 'kha-white/manga-ocr-base'
    │           └ <class 'manga_ocr.ocr.MangaOcr'>
    └ <mokuro.manga_page_ocr.MangaPageOcr object at 0x000002AF36512BE0>
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\manga_ocr\ocr.py", line 15, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path)
    │                │             │               └ 'kha-white/manga-ocr-base'
    │                │             └ <classmethod object at 0x000002AF36322BB0>
    │                └ <class 'transformers.models.auto.tokenization_auto.AutoTokenizer'>
    └ <manga_ocr.ocr.MangaOcr object at 0x000002AF36512BB0>
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\transformers\models\auto\tokenization_auto.py", line 528, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           │               │               │                               │         └ {'_from_auto': True}
           │               │               │                               └ ()
           │               │               └ 'kha-white/manga-ocr-base'
           │               └ <classmethod object at 0x000002AF362883D0>
           └ <class 'transformers.models.bert_japanese.tokenization_bert_japanese.BertJapaneseTokenizer'>
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\transformers\tokenization_utils_base.py", line 1780, in from_pretrained
    return cls._from_pretrained(
           │   └ <classmethod object at 0x000002AF36288490>
           └ <class 'transformers.models.bert_japanese.tokenization_bert_japanese.BertJapaneseTokenizer'>
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\transformers\tokenization_utils_base.py", line 1915, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                │    │              └ {'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]', 'do_lower_ca...
                │    └ ()
                └ <class 'transformers.models.bert_japanese.tokenization_bert_japanese.BertJapaneseTokenizer'>
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\transformers\models\bert_japanese\tokenization_bert_japanese.py", line 151, in __init__
    self.word_tokenizer = MecabTokenizer(
    │                     └ <class 'transformers.models.bert_japanese.tokenization_bert_japanese.MecabTokenizer'>
    └ PreTrainedTokenizer(name_or_path='kha-white/manga-ocr-base', vocab_size=6144, model_max_len=1000000000000000019884624838656, ...
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\transformers\models\bert_japanese\tokenization_bert_japanese.py", line 231, in __init__
    import fugashi
  File "C:\Users\Seven7\AppData\Roaming\Python\Python39\site-packages\fugashi\__init__.py", line 1, in <module>
    from .fugashi import *

ImportError: DLL load failed while importing fugashi: The specified module could not be found.
2022-05-05 13:18:19.552 | INFO     | mokuro.run:run:48 - Processed successfully: 0/1
```

**Comment by kha-white** [comment]
Are you using Python from Microsoft Store? If so, try installing it from Python website instead: https://www.python.org/downloads/

**Comment by YinnVI** [comment]
fixed just copy libmecab.dll to site-packages/fugashi

**Comment by jamesnicolas** [comment]
Commenting since downloading from the official site didn't solve my issue. I uninstalled all of my python installations and installed 3.9 and 3.10 (pytorch supports 3.10 now) from the official Python website, but both still gave me the error. The comment above mentions the fix but just to specifically document what I did: (Note I already had CUDA and torch installed)

- Go to https://pypi.org/project/fugashi/#files
- Download the file corresponding to your Python version. found the corresponding python version, (since I was on python 3.10 and on windows, I chose `fugashi-1.2.1-cp310-cp310-win_amd64.whl`.
- Rename the .whl file to .zip
- To find the path where fugashi was supposed to be installed, I checked the error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\james\AppData\Roaming\Python\Python310\site-packages\fugashi\__init__.py", line 1, in <module>
    from .fugashi import *
ImportError: DLL load failed while importing fugashi: 指定されたモジュールが見つ
かりません。
```

- And I noted `C:\Users\james\AppData\Roaming\Python\Python310\site-packages\fugashi`
- In the zip file, I went to `fugashi-1.2.1.data\data\lib\site-packages\fugashi` and extracted out the `libmecab.dll` file and copied it to the fugashi folder that I noted earlier
- I ran mokuro, saw the log saying "Using CUDA", and everything worked!
